### ISSUE TITLE
Cryptorave statement translation to Spanish 

### ISSUE THREAD

**Issue by rafaelbonifaz** [freeolabini/freeolabini.github.io#168]
I believe that the translation of the third sentence in the first paragraph has an error.
From: https://freeolabini.org/en/statement-cryptorave/

As they dared, we too shall dare. Even though we have all to loose, as any other Latin American citizen that goes against what power wants. **But they dared against us, the people.** They dared to incarcerate whomever and whenever they want without any evidence. They dared to confuse the privacy and security work we do as criminal activity, and to call it that way. We shall dare then to, at least, let our voice be heard.

The Spanish version goes like this:
Como ellos osaron, nosotros también osaremos. Aunque tengamos todo que perder, como ciudadanos latinoamericanos que van en contra de lo que quiere el poder. **Ya que ellos osaron, nosotros también osaremos**. Ellos se atrevieron a detener a quien quieran cuando quisieran, sin ninguna evidencia. Ellos osaron confundir el trabajo de privacidad y seguridad que hacemos como una actividad criminal, y llamarla así. Osaremos, entonces, por lo menos, a hacer que nuestra voz sea oída.

I believe it should say something like: "Pero se atrevieron contra nosotros, la gente."  or "Pero se atrevieron contra nosotros, el pueblo."

**Comment by claucece** [comment]
Solved.
