### ISSUE TITLE
Forthcoming sections?

### ISSUE THREAD

**Issue by paul-hammant** [freeolabini/freeolabini.github.io#17]
Is there a place here for character references and "he's an ordinary human stories" ?

**Comment by dmytri** [comment]
Maybe just a post? in _src/en (if it's english?)

**Comment by paul-hammant** [comment]
To go into a new place in the information architecture ?

`https://freeolabini.org/<lang>/who-is-he/`

**Comment by dmytri** [comment]
sure, that works for me, or maybe: /about-ola

**Comment by paul-hammant** [comment]
See https://github.com/freeolabini/freeolabini.github.io/pull/120
