### ISSUE TITLE
Create a section where the art can be downloaded

### ISSUE THREAD

**Issue by claucece** [freeolabini/freeolabini.github.io#200]
So people can download the logo, flyers strikers designs to print them.

**Comment by claucece** [comment]
@dmytri @iliasbartolini

**Comment by dmytri** [comment]
OK, will try to get to that in the next couple of days

**Comment by iliasbartolini** [comment]
A couple of notes. 
Today I'll refine the designs, clean the page and add a couple more examples.

The English version is linked across all languages. 
I was thinking it was better to create language specific pages only after the media files are translated too.
Meanwhile the navigation might appear confusing after landing to the media kit page, so now I changed my mind and I'll fix this :)

**Comment by iliasbartolini** [comment]
I would close this when PR #223 i merged
