### ISSUE TITLE
 A suscribe for updates on the case

### ISSUE THREAD

**Issue by dtiradob** [freeolabini/freeolabini.github.io#3]
Implement a subscription method for updates on the case. 
should be GDPR compliant.

**Comment by dmytri** [comment]
Isn't following the FreeOlaBini twitter account the best way to do this? Or are we looking for something email based?

**Comment by dtiradob** [comment]
I think they would want something email based.

**Comment by MauroVelasco** [comment]
do you agree with add a telegram group for that?

**Comment by rafaelbonifaz** [comment]
I would suggest something like riseup for that

**Comment by rafaelbonifaz** [comment]
The newsletter has been created

**Comment by dtiradob** [comment]
thanks @rbonfaz we have the newsletter now. Any suggestion on how to add a subscribe form to the website?

**Comment by pedropalau** [comment]
@dtiradob There should be a new link to subscribe page accessible from the front-page.

Kindly review the changes and close the ticket.

**Comment by dtiradob** [comment]
Thank you!
