### ISSUE TITLE
Highlighted Tweets 

### ISSUE THREAD

**Issue by dtiradob** [freeolabini/freeolabini.github.io#5]
there is a request to add highlighted tweets of support at the top. 
will get the links

**Comment by dmytri** [comment]
Do you mean specific tweets or a feed? i.e. what is tweeted by @FreeOlaBini?

**Comment by dtiradob** [comment]
Specific tweets, im still trying to get the ones that they want.

**Comment by claucece** [comment]
These ones at least:

https://twitter.com/davidakaye/status/1117489081397547008

https://twitter.com/EdisonLanza/status/1117552044737429504

**Comment by rafaelbonifaz** [comment]
It should be nice to have support statements from organizations. Here are some: 
- APC.-    Assange and Bini's arrests, a serious threat to freedom of expression worldwide https://www.apc.org/en/news/assange-and-binis-arrests-serious-threat-freedom-expression-worldwide
- Article 19.- Ecuador: Arrest of Ola Bini, prominent Swedish software developer https://www.article19.org/resources/ecuador-arrest-of-ola-bini-prominent-swedish-software-developer/
-  Tor Project.- Ecuador: Free Ola Bini https://blog.torproject.org/ecuador-free-ola-bini

**Comment by claucece** [comment]
Also: https://twitter.com/ErikaGuevaraR/status/1117791352488628224

**Comment by sacurio** [comment]
Do you thing these tweets should be included? https://twitter.com/article19org/status/1117789379802673152
https://twitter.com/torproject/status/1117802702489235458
https://twitter.com/confeniae1/status/1117789695382040577
https://twitter.com/Gabitegui/status/1117854425576505348

**Comment by claucece** [comment]
These ones:

> https://twitter.com/article19org/status/1117789379802673152
https://twitter.com/torproject/status/1117802702489235458
https://twitter.com/confeniae1/status/1117789695382040577

Yes.

**Comment by pedropalau** [comment]
There is a new feature where you can add new tweets using markdown and pull requests. 

You can read more about it [here](https://github.com/freeolabini/freeolabini.github.io/blob/master/ADDING-TWEETS.md).

@dtiradob can you kindly review and then close the ticket?
