### ISSUE TITLE
Improve better sign method

### ISSUE THREAD

**Issue by jonathanf** [freeolabini/freeolabini.github.io#58]
I think could be great if we implement 2 improves in the signature "method":

1. Add a signants counter
2. Dev the functionality to create a form who allow the signant:
    - Registry of personal name o organization name, email, website, support text as no mandatory
    - Send a verification email 
    - Thank you page with sharing options

**Comment by dmytri** [comment]
good idea, but low priority for now since we need to vet the signatories in anycase.
