### ISSUE TITLE
Low severity vul in dependence @11ty/eleventy

### ISSUE THREAD

**Issue by jonathanf** [freeolabini/freeolabini.github.io#66]
I got a lsv message in static code gen:

review
braces
low	>=2.3.1
Regular Expression Denial of Service
https://nodesecurity.io/advisories/786
@11ty/eleventy>browser-sync>micromatch>braces

**Comment by dmytri** [comment]
This is related to browsersync, which the dev server, it does not affect 11ty generated sites. 11ty is award if of it, and will upgrade once browsersync does

**Comment by dmytri** [comment]
Actualy @jonathanf, can you find the information and update the README?
