### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jorgesumle** [freeolabini/freeolabini.github.io#88]
I was thinking about submitting an Esperanto translation, but I only contribute translations to free software or free culture projects, can you please specify a license?

**Comment by dmytri** [comment]
We're still open, is there a license you like that we should consider?

**Comment by jorgesumle** [comment]
I don't care about the software license, as long as it's [free software](https://www.gnu.org/licenses/license-list.en.html). Maybe AGPLv3?

About the content, which is what I'm interested as a translator I think something [Creative Commons Attribution-ShareAlike](https://creativecommons.org/licenses/by-sa/4.0/deed.en) is a great option. But again, I don't care as long as it's free culture. Apart from the [icon](https://en.wikipedia.org/wiki/File:CC-BY-SA_icon.svg) somewhere (usually the footer), it's also a good idea to specify a license as a link element: `<link rel="license" hreflang="en" href="https://creativecommons.org/licenses/by-sa/4.0/deed.en">` inside the `<head>`.

**Comment by dmytri** [comment]
Sounds good, feel free to specify above in pull request.
